import React from "react";
const columns = [
    { name: "ID", uid: "id" },
    { name: "TITLE", uid: "title" },
    { name: "DESCRIPTION", uid: "description" },
    { name: "STATUS", uid: "status" },
    { name: "VOTES", uid: "votes" },
    { name: "RAISED BY", uid: "raisedby" },
    { name: "ACTIONS", uid: "actions" },
];

const users: any = [
    {
        id: 1,
        title: "TEST1",
        status: "IN_REVIEW",
        description: "Description of project 1",
        votes: "1",
        avatar: "https://static.vecteezy.com/system/resources/previews/000/512/317/non_2x/vector-wallet-glyph-black-icon.jpg",
        raisedby: "0xqdjdhasd28347823489jk234ffsf",
    },
    {
        id: 2,
        title: "TEST2",
        status: "IN_REVIEW",
        description: "Description of project 2",
        votes: "2",
        avatar: "https://static.vecteezy.com/system/resources/previews/000/512/317/non_2x/vector-wallet-glyph-black-icon.jpg",
        raisedby: "0xqdjdhasd28347823489jk234ffsf",
    },
    {
        id: 4,
        title: "TEST3",
        status: "DONE",
        description: "Description of project 3",
        votes: "9",
        avatar: "https://static.vecteezy.com/system/resources/previews/000/512/317/non_2x/vector-wallet-glyph-black-icon.jpg",
        raisedby: "0xqdjdhasd28347823489jk234ffsf",
    },
    {
        id: 4,
        title: "TEST3",
        status: "DONE",
        description: "Description of project 3",
        votes: "9",
        avatar: "https://static.vecteezy.com/system/resources/previews/000/512/317/non_2x/vector-wallet-glyph-black-icon.jpg",
        raisedby: "0xqdjdhasd28347823489jk234ffsf",
    },
    {
        id: 4,
        title: "TEST3",
        status: "NEW",
        description: "Description of project 3",
        votes: "9",
        avatar: "https://static.vecteezy.com/system/resources/previews/000/512/317/non_2x/vector-wallet-glyph-black-icon.jpg",
        raisedby: "0xqdjdhasd28347823489jk234ffsf",
    },
    {
        id: 4,
        title: "TEST3",
        status: "REJ",
        description: "Description of project 3",
        votes: "9",
        avatar: "https://static.vecteezy.com/system/resources/previews/000/512/317/non_2x/vector-wallet-glyph-black-icon.jpg",
        raisedby: "0xqdjdhasd28347823489jk234ffsf",
    },
    {
        id: 4,
        title: "TEST3",
        status: "REJ",
        description: "Description of project 3",
        votes: "9",
        avatar: "https://static.vecteezy.com/system/resources/previews/000/512/317/non_2x/vector-wallet-glyph-black-icon.jpg",
        raisedby: "0xqdjdhasd28347823489jk234ffsf",
    },
    {
        id: 4,
        title: "TEST3",
        status: "DEF",
        description: "Description of project 3",
        votes: "9",
        avatar: "https://static.vecteezy.com/system/resources/previews/000/512/317/non_2x/vector-wallet-glyph-black-icon.jpg",
        raisedby: "0xqdjdhasd28347823489jk234ffsf",
    },
    {
        id: 4,
        title: "TEST3",
        status: "DEF",
        description: "Description of project 3",
        votes: "9",
        avatar: "https://static.vecteezy.com/system/resources/previews/000/512/317/non_2x/vector-wallet-glyph-black-icon.jpg",
        raisedby: "0xqdjdhasd28347823489jk234ffsf",
    },
    {
        id: 4,
        title: "TEST3",
        status: "DEF",
        description: "Description of projectfdfdfdfdfdfdfwerwerdfjsdfhsdufdsufhdufhdfudhfdushfdufhdsufhduhdufhdsufhdufhdsufhdfdufh 3",
        votes: "9",
        avatar: "https://static.vecteezy.com/system/resources/previews/000/512/317/non_2x/vector-wallet-glyph-black-icon.jpg",
        raisedby: "0xqdjdhasd28347823489jk234ffsf",
    },

];

export { columns, users };
